### ISSUE TITLE
Need help modifying emailEnv.ts file 

### ISSUE THREAD

**Issue by ouDriss95** [Kazuki-tam/shopify-email-notification#12]
Firstly, thank you so much for creating this tool to help Shopify theme developers. I would like any guides on how I can activate images in emailEnv.ts file since I have no experience in typeScript! Will be grateful if you tell me how. Thanks

**Comment by Kazuki-tam** [comment]
@ouDriss95 
Thank you for commenting and for letting me know!

I noticed that I couldn't set the `img_url` filter in this project. 
Please consider the following answer until I resolve this issue.

emailEnv.ts file:
```
   // Add image url
    image: "https://cdn.shopify.com/s/files/1/xxxxx/x.png",
    product: {
      title: 'Aviator sunglasses',
    },
```

liquid file:
line -> line.image
```
<img src='{{ line.image | img_url: 'compact_cropped' }}' align='left' width='60'  height='60' class='order-list__product-image'>
```

**Comment by ouDriss95** [comment]
Thanks for providing me this solution, wish you the best on resolving this issue

**Comment by Kazuki-tam** [comment]
@ouDriss95 
I added `img_url` filter.  There will be no need to change liquid files.

https://github.com/Kazuki-tam/shopify-email-notification/blob/main/server/filters/imgUrl.ts

**Comment by ouDriss95** [comment]
Oh, that's awesome! Thanks for letting me know
